version: 0.1

phases:
  build:
    commands:
      - echo Entered the build phase...
      - mvn clean package
  post_build:
    commands:
      - echo Build completed successfully
artifacts:
  files:
    - target/jagirdars-jmart-application-1.0.0.jar
  discard-paths: yes